service: first-project

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 512
  environment:
    test: test-env-value

functions:
  hello:
    handler: handler.hello
