service: first-project

frameworkVersion: "2 || 3"

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 512
  environment:
    test: test-env-value
    test_ssm_string: ${ssm:/test/string}
    test_ssm_secure_string: ${ssm:/test/secure_string}

functions:
  hello:
    handler: handler.hello
