# This is a basic workflow to help you get started with Actions

name: Main Deployment Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [stage1, prod1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-18.04

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # Runs a single command using the runners shell
  #     - name: Initial build setup
  #       run: npm install -g serverless

  deploy_dev:
    name: Dev deployment
    # needs: build
    if: github.ref == 'refs/heads/stage1'
    environment: STAGE
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Print dev secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: echo Running from branch $GITHUB_REF
      - name: Configure AWS credentials from OIDC account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::666025726922:role/github-action-assume-role
          aws-region: ap-south-1
      # - name: Read ssm param
      #   run: echo /test/string=$(aws ssm get-parameter --name "/test/string" --query "Parameter.Value" --output text)
      - name: Install serverless
        run: npm install -g serverless@2.72.2
      - name: Print serverless version
        run: serverless -v
      - name: Deploy serverless
        run: serverless deploy

  deploy_prod:
    name: Prod deployment
    # needs: build
    if: github.ref == 'refs/heads/prod1'
    environment: PRODUCTION
    runs-on: ubuntu-18.04
    steps:
      - name: Print prod secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: echo Running from branch $GITHUB_REF
