# This is a basic workflow to help you get started with Actions

name: Main Deployment Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [stage, prod]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Initial build setup
        run: echo Hello from build-setup

  deploy_dev:
    name: Dev deployment
    needs: build
    environment: STAGE
    runs-on: ubuntu-18.04
    steps:
      - name: Print dev secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: echo AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
